export const data =  {
  themeGroup:  [
    'Alimentation citoyenne, responsable',
    'Commerce equitable',
    'Enjeux alimentaires globaux',
    'Equilibre alimentaire et nutrition',
    'Gestion budgétaire',
    'Gout et autres sens',
    'Idées reçues sur l\'alimentation',
    'Jardinage',
    'Métiers',
    'Montage de projet',
    'Patrimoine culturel et alimentaire',
    'Pratiques agricoles',
    'Préparation culinaire',
    'Pratique de médiation, d\'animation',
    'Autres'
  ],
  populationTarget:  [
    'Enfants',
    'Adolescents',
    'Adultes',
    'Jeunes',
    'Tous publics',
    '3 - 6 ans',
    '6 - 10 ans',
    '10 - 14 ans',
    '14 - 18 ans',
    '18 - 25 ans',
    'Porteurs de projet'
    ],
  format: [
    'Information non disponible',
    'Physique',
    'Numérique',
    'Physique et numérique',
  ],
   cost: [
    'Payant',
    'Gratuit',
    'Gratuit ou payant suivant le format',
    'Formation de prise en main payante',
    'Location payante',
    'Frais de transport à payer',
  ],
   toolType: [
    'Activité, technique d\'animation',
    'Affiche',
    'Applications multimédia',
    'Conférence',
    'Documentaire',
    'Exposition interactive',
    'Fiche d\'information',
    'Fiche ressource',
    'Film',
    'Guide méthodologique',
    'Jeux',
    'Livre',
    'Livret et guide pédagogique',
    'Malle pédagogique',
    'Malle pédagogique avec matériel',
    'Malle pédagogique sans matériel',
    'Manuel, tutoriel',
    'Recueil d\'outils pédagogiques',
    'Site web',
    'Tutoriel',
    'Vidéo courte',
  ]
};
