version: '3.5'
services:
  traefik:
    image: traefik:v2.3
    container_name: traefik_100lieux
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=lhomme.thomas@pm.me"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  fuseki:
    image: stain/jena-fuseki:3.10.0
    container_name: fuseki_100Lieux
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build: middleware
    container_name: middleware_100lieux
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./middleware/logs:/app/logs
      - ./middleware/actors:/app/actors
      - ./middleware/jwt:/app/jwt
      - ./middleware/uploads:/app/uploads
      - ./data/fuseki/backups:/app/fuseki-backups # Needed to backup fuseki datasets
    ports:
      - "3000:3000"
    expose:
      - "3000"
    #labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.middleware.rule=Host(`data.classe-dehors.org`)"
      # - "traefik.http.routers.middleware.entrypoints=websecure"
      #-  "traefik.http.routers.middleware.tls.certresolver=myresolver"

  frontend:
    build: frontend
    container_name: frontend_100Lieux
    restart: always
    depends_on:
      - middleware
    ports:
      - 4200:80
    expose:
      - 4200
    volumes:
            - ./frontend:/usr/src/app/frontend
            - /usr/src/app/frontend/node_modules
    #labels:
     # - "traefik.enable=true"
     # - "traefik.http.routers.frontend.rule=Host(`classe-dehors.org`)"
     # - "traefik.http.routers.frontend.entrypoints=websecure"
     # - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  redis:
    image: redis
    container_name: redis_100lieux
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]
